#!/usr/bin/env python

from lpout.client import Client

client = Client()
project = client.project('inkscape-web')

def import_bug(cls, name, data, parent=None):
    print "Bug: %s" % str(name)
    print data

def import_user(cls, name, data, parent=None):
    print "User: %s" % str(name)
    print data

def import_milestone(cls, name, data, parent=None):
    print "Milestone: %s" % str(name)
    print data

def import_comment(cls, name, data, parent=None):
    print " - Comment: %s" % str(name)
    print data

def import_label(cls, name, data, parent=None):
    print " + Label: %s" % str(name)
    print data

Client.connect(
    Bug=import_bug,
    User=import_user,
    Milestone=import_milestone,
    Label=import_label,
)

for bug in project.get_bugs():
    pass

